name: Build News

on:
  workflow_dispatch:
  schedule:
    # Run every hour to refresh the news feed
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies required for the fetch script
      - name: Install dependencies
        run: npm init -y && npm i xml2js jsdom dompurify

      - name: Build news artifacts
        run: node scripts/fetch-news.mjs

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/news.json docs/embed.html docs/index.html
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "news: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
